"""
Django settings for EGNSite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Load deploy/.env when present so production secrets stay out of git.
# On a dev machine there is no .env and every setting below falls back to the
# original hardcoded value, so local behaviour is unchanged.
#
# PRECEDENCE: load_dotenv defaults to override=False, so a variable already in
# the environment BEATS the file. That is correct for systemd (which passes the
# same values via EnvironmentFile=), but it means a shell that has sourced an
# older copy of .env will silently shadow the current one -- producing a
# database "Access denied" that survives fixing the password, and that appears
# to be cured by sudo (which resets the environment). Do not source .env by
# hand; this call is the only loader you need. See docs/operations.md.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR.parent / 'deploy' / '.env')
except ImportError:
    pass


def _env_list(name, default=''):
    """Read a comma-separated env var into a list, ignoring blanks."""
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]

LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The literal below is the historical dev key and is public in git history.
# Production MUST override it via DJANGO_SECRET_KEY in deploy/.env.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'efiy#i9cg+dw!i+b+$6&t7v2r5rjc=@h31t2e&w#r)9z2c*gp0',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

APPEND_SLASH = True

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS') or [
    'www.sciencelabtoyou.com',
    'localhost',
    '127.0.0.1',
    #ALL NGROK DOMAINS
    '.ngrok.io',
    '.ngrok-free.app',
    '.ngrok-free.dev',
    'sciencelabtoyou.com',
]




CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(
                os.environ.get('REDIS_HOST', '127.0.0.1'),
                int(os.environ.get('REDIS_PORT', 6379)),
            )],
        },
    },
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MatlabApp',
    'accounts', 
    #'bootstrap5',	
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EGNSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
	'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#HTTP and web sockets
ASGI_APPLICATION = 'EGNSite.asgi.application'
WSGI_APPLICATION = 'EGNSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'egnsitedb'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles',  
]

STATIC_ROOT = BASE_DIR / 'collected_static'

# nginx terminates TLS and forwards plain HTTP to gunicorn. Without this,
# Django believes every request is insecure: request.is_secure() returns False,
# CSRF rejects POSTs whose Origin is https://, and the dashboard's command
# buttons fail with 403.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_SSL_REDIRECT = False          # nginx already redirects :80 -> :443

# Marking cookies Secure tells the browser to send them ONLY over HTTPS -- and
# to refuse to store them at all over plain HTTP. That makes login impossible
# while the site is still HTTP-only: the CSRF cookie is never saved and every
# POST fails with "this site requires a CSRF cookie when submitting forms".
#
# Defaults to on in production, but must be overridable, because deployment
# runs on HTTP first (the TLS nginx config cannot load before certbot has
# issued a certificate). Set DJANGO_COOKIE_SECURE=False during that window,
# then remove it once deploy/enable-tls.sh has run.
_cookie_secure_default = 'False' if DEBUG else 'True'
COOKIE_SECURE = os.environ.get(
    'DJANGO_COOKIE_SECURE', _cookie_secure_default
).lower() in ('1', 'true', 'yes')

SESSION_COOKIE_SECURE = COOKIE_SECURE
CSRF_COOKIE_SECURE = COOKIE_SECURE

# The deployed origin MUST be listed here or every POST from the dashboard is
# rejected. The previous config listed only ngrok domains and got away with it
# because DEBUG was True.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS') or [
    'https://sciencelabtoyou.com',
    'https://www.sciencelabtoyou.com',
    #ALL NGROK DOMAINS
    'https://*.ngrok.io',
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
