# Generated by Django 6.1 on 2026-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('view_only', 'View Only'), ('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=20),
        ),
    ]
