# Generated by Django 6.1 on 2026-09-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rolerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_instructor',
        ),
    ]
