# Generated by Django 6.1 on 2026-09-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatlabApp', '0009_alter_controllock_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('extraValue', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
