[project]
name = "webinterface"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref",
    "channels",
    "channels-redis",
    "django",
    "django-cors-headers",
    "gunicorn",
    "msgpack",
    "paho-mqtt",
    "pymysql",
    "python-dotenv",
    "redis",
    "sqlparse",
    "uvicorn[standard]",
]
